# Generated by Django 6.0.7 on 2026-07-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearStart', models.CharField(default='01 Apr', max_length=50)),
                ('yearEnd', models.CharField(default='31 Mar', max_length=50)),
                ('preDefinedLineItems', models.TextField(blank=True, default='')),
            ],
        ),
    ]
