# Generated by Django 6.0.7 on 2026-07-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoUrl', models.TextField(blank=True, default='', null=True)),
                ('businessName', models.TextField(blank=True, default='', null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('extraInfo', models.TextField(blank=True, default='', null=True)),
                ('website', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.TextField(blank=True, default='', null=True)),
                ('emailName', models.TextField(blank=True, default='', null=True)),
                ('bccClientEmails', models.TextField(blank=True, default='', null=True)),
                ('quoteSubject', models.TextField(blank=True, default='', null=True)),
                ('quoteContent', models.TextField(blank=True, default='', null=True)),
                ('quoteButtonText', models.TextField(blank=True, default='', null=True)),
                ('invoiceSubject', models.TextField(blank=True, default='', null=True)),
                ('invoiceContent', models.TextField(blank=True, default='', null=True)),
                ('invoiceButtonText', models.TextField(blank=True, default='', null=True)),
                ('paymentReceivedSubject', models.TextField(blank=True, default='', null=True)),
                ('paymentReceivedContent', models.TextField(blank=True, default='', null=True)),
                ('paymentReminderSubject', models.TextField(blank=True, default='', null=True)),
                ('paymentReminderContent', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtrasSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darkMode', models.TextField(blank=True, default='', null=True)),
                ('notifications', models.TextField(blank=True, default='', null=True)),
                ('maintenance', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.TextField(blank=True, default='', null=True)),
                ('suffix', models.TextField(blank=True, default='', null=True)),
                ('autoIncrement', models.TextField(blank=True, default='', null=True)),
                ('nextNumber', models.TextField(blank=True, default='', null=True)),
                ('dueDate', models.TextField(blank=True, default='', null=True)),
                ('hideAdjustField', models.TextField(blank=True, default='', null=True)),
                ('terms', models.TextField(blank=True, default='', null=True)),
                ('footer', models.TextField(blank=True, default='', null=True)),
                ('noticeInvoiceViewed', models.TextField(blank=True, default='', null=True)),
                ('noticeInvoicePaid', models.TextField(blank=True, default='', null=True)),
                ('customCss', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicensesSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, default='', null=True)),
                ('purchaseCode', models.TextField(blank=True, default='', null=True)),
                ('licenseKey', models.TextField(blank=True, default='', null=True)),
                ('expiry', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencySymbol', models.TextField(blank=True, default='', null=True)),
                ('currencyPosition', models.TextField(blank=True, default='', null=True)),
                ('thousandSeparator', models.TextField(blank=True, default='', null=True)),
                ('decimalSeparator', models.TextField(blank=True, default='', null=True)),
                ('numberOfDecimals', models.TextField(blank=True, default='', null=True)),
                ('paymentPage', models.TextField(blank=True, default='', null=True)),
                ('paymentPageFooter', models.TextField(blank=True, default='', null=True)),
                ('bankDetails', models.TextField(blank=True, default='', null=True)),
                ('genericPayment', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PdfSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(blank=True, default='', null=True)),
                ('paper', models.TextField(blank=True, default='', null=True)),
                ('orientation', models.TextField(blank=True, default='', null=True)),
                ('watermark', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuotesSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.TextField(blank=True, default='', null=True)),
                ('suffix', models.TextField(blank=True, default='', null=True)),
                ('autoIncrement', models.TextField(blank=True, default='', null=True)),
                ('nextNumber', models.TextField(blank=True, default='', null=True)),
                ('quotesValidFor', models.TextField(blank=True, default='', null=True)),
                ('hideAdjustField', models.TextField(blank=True, default='', null=True)),
                ('terms', models.TextField(blank=True, default='', null=True)),
                ('footer', models.TextField(blank=True, default='', null=True)),
                ('acceptQuoteButton', models.TextField(blank=True, default='', null=True)),
                ('acceptedQuoteAction', models.TextField(blank=True, default='', null=True)),
                ('acceptQuoteText', models.TextField(blank=True, default='', null=True)),
                ('acceptedQuoteMessage', models.TextField(blank=True, default='', null=True)),
                ('declineReasonRequired', models.TextField(blank=True, default='', null=True)),
                ('declinedQuoteMessage', models.TextField(blank=True, default='', null=True)),
                ('noticeQuoteViewed', models.TextField(blank=True, default='', null=True)),
                ('noticeQuoteAccepted', models.TextField(blank=True, default='', null=True)),
                ('customCss', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricesEnteredWithTax', models.TextField(blank=True, default='', null=True)),
                ('taxPercentage', models.TextField(blank=True, default='', null=True)),
                ('taxName', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteLabel', models.TextField(blank=True, default='', null=True)),
                ('quoteLabelPlural', models.TextField(blank=True, default='', null=True)),
                ('invoiceLabel', models.TextField(blank=True, default='', null=True)),
                ('invoiceLabelPlural', models.TextField(blank=True, default='', null=True)),
                ('hrsQty', models.TextField(blank=True, default='', null=True)),
                ('service', models.TextField(blank=True, default='', null=True)),
                ('ratePrice', models.TextField(blank=True, default='', null=True)),
                ('adjust', models.TextField(blank=True, default='', null=True)),
                ('subTotal', models.TextField(blank=True, default='', null=True)),
                ('discount', models.TextField(blank=True, default='', null=True)),
                ('total', models.TextField(blank=True, default='', null=True)),
                ('totalDue', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
