# Generated by Django 5.2.7 on 2026-07-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_delete_translatesetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteLabel', models.TextField(blank=True, default='', null=True)),
                ('quoteLabelPlural', models.TextField(blank=True, default='', null=True)),
                ('invoiceLabel', models.TextField(blank=True, default='', null=True)),
                ('invoiceLabelPlural', models.TextField(blank=True, default='', null=True)),
                ('hrsQty', models.TextField(blank=True, default='', null=True)),
                ('service', models.TextField(blank=True, default='', null=True)),
                ('ratePrice', models.TextField(blank=True, default='', null=True)),
                ('adjust', models.TextField(blank=True, default='', null=True)),
                ('subTotal', models.TextField(blank=True, default='', null=True)),
                ('discount', models.TextField(blank=True, default='', null=True)),
                ('total', models.TextField(blank=True, default='', null=True)),
                ('totalDue', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='emailssetting',
            old_name='mailFrom',
            new_name='emailAddress',
        ),
        migrations.RenameField(
            model_name='invoicessetting',
            old_name='notes',
            new_name='suffix',
        ),
        migrations.RenameField(
            model_name='quotessetting',
            old_name='notes',
            new_name='acceptQuoteText',
        ),
        migrations.RenameField(
            model_name='taxsetting',
            old_name='taxNumber',
            new_name='pricesIncludeTax',
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='bccOnClientEmails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='emailName',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='footerContent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='invoiceButtonText',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='invoiceContent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='invoiceSubject',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='paymentContent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='paymentSubject',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='quoteButtonText',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='quoteContent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='quoteSubject',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='reminderContent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='reminderDays',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='emailssetting',
            name='reminderSubject',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='invoicessetting',
            name='autoIncrement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoicessetting',
            name='customCss',
            field=models.TextField(blank=True, default='body {}', null=True),
        ),
        migrations.AddField(
            model_name='invoicessetting',
            name='hideAdjustField',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicessetting',
            name='noticePaid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoicessetting',
            name='noticeViewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicessetting',
            name='template',
            field=models.TextField(blank=True, default='Template 1', null=True),
        ),
        migrations.AddField(
            model_name='invoicessetting',
            name='terms',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='paymentssetting',
            name='bankDetails',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='paymentssetting',
            name='currencyPosition',
            field=models.TextField(blank=True, default='left', null=True),
        ),
        migrations.AddField(
            model_name='paymentssetting',
            name='currencySymbol',
            field=models.TextField(blank=True, default='₹', null=True),
        ),
        migrations.AddField(
            model_name='paymentssetting',
            name='decimalSeparator',
            field=models.TextField(blank=True, default='.', null=True),
        ),
        migrations.AddField(
            model_name='paymentssetting',
            name='genericPayment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='paymentssetting',
            name='numberOfDecimals',
            field=models.TextField(blank=True, default='2', null=True),
        ),
        migrations.AddField(
            model_name='paymentssetting',
            name='paymentPage',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='paymentssetting',
            name='paymentPageFooter',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='paymentssetting',
            name='paypalGateway',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='paymentssetting',
            name='thousandSeparator',
            field=models.TextField(blank=True, default=',', null=True),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='acceptQuoteButton',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='acceptedQuoteAction',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='acceptedQuoteMessage',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='autoIncrement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='customCss',
            field=models.TextField(blank=True, default='body {}', null=True),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='declineReasonRequired',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='declinedQuoteMessage',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='footer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='hideAdjustField',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='noticeAccepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='noticeViewed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='suffix',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='quotessetting',
            name='template',
            field=models.TextField(blank=True, default='Template 3', null=True),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='preDefinedLineItems',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
