# Generated by Django 6.0.7 on 2026-07-22 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Credit Card', 'Credit Card'), ('Cash', 'Cash')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
